---
app_name: istrosec
app_environment: development
app_image: ghcr.io/metjumetju/istrosec:main
app_container_name: "{{ app_name }}"
app_container_port: 5000
app_host_port: "{{ app_container_port }}"
app_project_dir: "/opt/{{ app_name }}"
app_restart_policy: unless-stopped
app_registry: ghcr.io
