---
all:
  children:
    docker_hosts:
      children:
        app_servers:
          hosts:
            dev-app01:
              ansible_host: 192.168.0.215
              ansible_user: mates
            dev-app02:
              ansible_host: 192.168.0.215
              ansible_user: mates
